from decimal import Decimal
from src import scenario3


def test_scenario3():
    result = scenario3.main()
    expected_result = [
        {
            "k": 3,
            "return": Decimal("47.9"),
            "volatility": Decimal("21.5"),
            "turnover": Decimal("54.6"),
            "drawdown": Decimal("-44.3"),
            "sharpe": Decimal("-3.6"),
        },
        {
            "k": 4,
            "return": Decimal("39.8"),
            "volatility": Decimal("21.0"),
            "turnover": Decimal("61.6"),
            "drawdown": Decimal("-40.0"),
            "sharpe": Decimal("-4.1"),
        },
        {
            "k": 5,
            "return": Decimal("64.2"),
            "volatility": Decimal("20.1"),
            "turnover": Decimal("69.7"),
            "drawdown": Decimal("-41.0"),
            "sharpe": Decimal("-3.1"),
        },
        {
            "k": 6,
            "return": Decimal("63.3"),
            "volatility": Decimal("19.7"),
            "turnover": Decimal("65.7"),
            "drawdown": Decimal("-39.4"),
            "sharpe": Decimal("-3.2"),
        },
        {
            "k": 7,
            "return": Decimal("74.7"),
            "volatility": Decimal("19.4"),
            "turnover": Decimal("69.0"),
            "drawdown": Decimal("-29.5"),
            "sharpe": Decimal("-2.6"),
        },
        {
            "k": 8,
            "return": Decimal("100.9"),
            "volatility": Decimal("18.6"),
            "turnover": Decimal("68.3"),
            "drawdown": Decimal("-25.9"),
            "sharpe": Decimal("-1.3"),
        },
        {
            "k": 9,
            "return": Decimal("97.7"),
            "volatility": Decimal("18.2"),
            "turnover": Decimal("66.3"),
            "drawdown": Decimal("-26.4"),
            "sharpe": Decimal("-1.5"),
        },
        {
            "k": 10,
            "return": Decimal("106.2"),
            "volatility": Decimal("18.0"),
            "turnover": Decimal("65.9"),
            "drawdown": Decimal("-25.9"),
            "sharpe": Decimal("-1.1"),
        },
        {
            "k": 11,
            "return": Decimal("149.1"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("65.8"),
            "drawdown": Decimal("-21.6"),
            "sharpe": Decimal("1.3"),
        },
        {
            "k": 12,
            "return": Decimal("172.3"),
            "volatility": Decimal("17.0"),
            "turnover": Decimal("55.3"),
            "drawdown": Decimal("-23.5"),
            "sharpe": Decimal("2.7"),
        },
        {
            "k": 13,
            "return": Decimal("133.1"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("52.1"),
            "drawdown": Decimal("-29.1"),
            "sharpe": Decimal("0.4"),
        },
        {
            "k": 14,
            "return": Decimal("143.6"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("50.7"),
            "drawdown": Decimal("-27.8"),
            "sharpe": Decimal("1.0"),
        },
        {
            "k": 15,
            "return": Decimal("159.8"),
            "volatility": Decimal("17.2"),
            "turnover": Decimal("48.6"),
            "drawdown": Decimal("-27.6"),
            "sharpe": Decimal("2.0"),
        },
        {
            "k": 16,
            "return": Decimal("155.0"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("48.8"),
            "drawdown": Decimal("-27.0"),
            "sharpe": Decimal("1.7"),
        },
        {
            "k": 17,
            "return": Decimal("127.1"),
            "volatility": Decimal("17.0"),
            "turnover": Decimal("46.3"),
            "drawdown": Decimal("-27.4"),
            "sharpe": Decimal("0.1"),
        },
        {
            "k": 18,
            "return": Decimal("120.8"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("44.9"),
            "drawdown": Decimal("-26.7"),
            "sharpe": Decimal("-0.3"),
        },
        {
            "k": 19,
            "return": Decimal("114.8"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("44.4"),
            "drawdown": Decimal("-27.3"),
            "sharpe": Decimal("-0.6"),
        },
        {
            "k": 20,
            "return": Decimal("90.8"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("43.3"),
            "drawdown": Decimal("-27.6"),
            "sharpe": Decimal("-2.0"),
        },
    ]

    assert result == expected_result
