from decimal import Decimal
from src import scenario4


def test_scenario4():
    result = scenario4.main()
    expected_result = [
        {
            "k": 3,
            "return": Decimal("57.6"),
            "volatility": Decimal("19.8"),
            "turnover": Decimal("49.1"),
            "drawdown": Decimal("-33.8"),
            "sharpe": Decimal("-3.4"),
        },
        {
            "k": 4,
            "return": Decimal("73.9"),
            "volatility": Decimal("19.3"),
            "turnover": Decimal("55.6"),
            "drawdown": Decimal("-27.2"),
            "sharpe": Decimal("-2.7"),
        },
        {
            "k": 5,
            "return": Decimal("56.1"),
            "volatility": Decimal("18.7"),
            "turnover": Decimal("59.3"),
            "drawdown": Decimal("-33.1"),
            "sharpe": Decimal("-3.7"),
        },
        {
            "k": 6,
            "return": Decimal("78.4"),
            "volatility": Decimal("18.7"),
            "turnover": Decimal("56.7"),
            "drawdown": Decimal("-29.8"),
            "sharpe": Decimal("-2.5"),
        },
        {
            "k": 7,
            "return": Decimal("83.3"),
            "volatility": Decimal("18.5"),
            "turnover": Decimal("60.4"),
            "drawdown": Decimal("-27.1"),
            "sharpe": Decimal("-2.3"),
        },
        {
            "k": 8,
            "return": Decimal("103.7"),
            "volatility": Decimal("18.1"),
            "turnover": Decimal("57.9"),
            "drawdown": Decimal("-23.6"),
            "sharpe": Decimal("-1.2"),
        },
        {
            "k": 9,
            "return": Decimal("108.8"),
            "volatility": Decimal("17.9"),
            "turnover": Decimal("55.2"),
            "drawdown": Decimal("-26.3"),
            "sharpe": Decimal("-0.9"),
        },
        {
            "k": 10,
            "return": Decimal("127.3"),
            "volatility": Decimal("17.7"),
            "turnover": Decimal("56.3"),
            "drawdown": Decimal("-27.0"),
            "sharpe": Decimal("0.1"),
        },
        {
            "k": 11,
            "return": Decimal("139.6"),
            "volatility": Decimal("17.4"),
            "turnover": Decimal("56.1"),
            "drawdown": Decimal("-25.0"),
            "sharpe": Decimal("0.8"),
        },
        {
            "k": 12,
            "return": Decimal("150.8"),
            "volatility": Decimal("17.0"),
            "turnover": Decimal("48.4"),
            "drawdown": Decimal("-26.6"),
            "sharpe": Decimal("1.5"),
        },
        {
            "k": 13,
            "return": Decimal("115.7"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("44.9"),
            "drawdown": Decimal("-30.6"),
            "sharpe": Decimal("-0.6"),
        },
        {
            "k": 14,
            "return": Decimal("130.3"),
            "volatility": Decimal("17.2"),
            "turnover": Decimal("43.7"),
            "drawdown": Decimal("-29.5"),
            "sharpe": Decimal("0.3"),
        },
        {
            "k": 15,
            "return": Decimal("153.7"),
            "volatility": Decimal("17.2"),
            "turnover": Decimal("42.1"),
            "drawdown": Decimal("-27.6"),
            "sharpe": Decimal("1.6"),
        },
        {
            "k": 16,
            "return": Decimal("152.1"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("40.5"),
            "drawdown": Decimal("-27.0"),
            "sharpe": Decimal("1.6"),
        },
        {
            "k": 17,
            "return": Decimal("142.5"),
            "volatility": Decimal("17.1"),
            "turnover": Decimal("38.3"),
            "drawdown": Decimal("-25.6"),
            "sharpe": Decimal("1.0"),
        },
        {
            "k": 18,
            "return": Decimal("125.9"),
            "volatility": Decimal("17.2"),
            "turnover": Decimal("39.0"),
            "drawdown": Decimal("-25.5"),
            "sharpe": Decimal("0.0"),
        },
        {
            "k": 19,
            "return": Decimal("121.3"),
            "volatility": Decimal("17.2"),
            "turnover": Decimal("37.6"),
            "drawdown": Decimal("-25.8"),
            "sharpe": Decimal("-0.3"),
        },
        {
            "k": 20,
            "return": Decimal("105.8"),
            "volatility": Decimal("17.2"),
            "turnover": Decimal("37.3"),
            "drawdown": Decimal("-27.5"),
            "sharpe": Decimal("-1.2"),
        },
    ]

    assert result == expected_result
