from decimal import Decimal
from src import scenario5


def test_scenario5():
    result = scenario5.main()
    expected_result = [
        {
            "k": 3,
            "return": Decimal("69.1"),
            "volatility": Decimal("19.8"),
            "turnover": Decimal("50.6"),
            "drawdown": Decimal("-31.2"),
            "sharpe": Decimal("-2.9"),
        },
        {
            "k": 4,
            "return": Decimal("73.0"),
            "volatility": Decimal("19.3"),
            "turnover": Decimal("55.7"),
            "drawdown": Decimal("-26.0"),
            "sharpe": Decimal("-2.7"),
        },
        {
            "k": 5,
            "return": Decimal("78.2"),
            "volatility": Decimal("18.5"),
            "turnover": Decimal("61.1"),
            "drawdown": Decimal("-31.5"),
            "sharpe": Decimal("-2.6"),
        },
        {
            "k": 6,
            "return": Decimal("84.1"),
            "volatility": Decimal("18.4"),
            "turnover": Decimal("57.5"),
            "drawdown": Decimal("-27.9"),
            "sharpe": Decimal("-2.3"),
        },
        {
            "k": 7,
            "return": Decimal("86.7"),
            "volatility": Decimal("18.1"),
            "turnover": Decimal("61.1"),
            "drawdown": Decimal("-23.4"),
            "sharpe": Decimal("-2.1"),
        },
        {
            "k": 8,
            "return": Decimal("95.1"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("58.7"),
            "drawdown": Decimal("-22.3"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 9,
            "return": Decimal("103.8"),
            "volatility": Decimal("17.5"),
            "turnover": Decimal("55.6"),
            "drawdown": Decimal("-24.8"),
            "sharpe": Decimal("-1.2"),
        },
        {
            "k": 10,
            "return": Decimal("122.7"),
            "volatility": Decimal("17.3"),
            "turnover": Decimal("56.0"),
            "drawdown": Decimal("-24.7"),
            "sharpe": Decimal("-0.2"),
        },
        {
            "k": 11,
            "return": Decimal("152.4"),
            "volatility": Decimal("17.0"),
            "turnover": Decimal("56.0"),
            "drawdown": Decimal("-21.5"),
            "sharpe": Decimal("1.6"),
        },
        {
            "k": 12,
            "return": Decimal("163.7"),
            "volatility": Decimal("16.6"),
            "turnover": Decimal("47.7"),
            "drawdown": Decimal("-24.5"),
            "sharpe": Decimal("2.3"),
        },
        {
            "k": 13,
            "return": Decimal("132.9"),
            "volatility": Decimal("16.7"),
            "turnover": Decimal("45.2"),
            "drawdown": Decimal("-28.2"),
            "sharpe": Decimal("0.4"),
        },
        {
            "k": 14,
            "return": Decimal("145.9"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("44.0"),
            "drawdown": Decimal("-27.4"),
            "sharpe": Decimal("1.2"),
        },
        {
            "k": 15,
            "return": Decimal("170.7"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("42.4"),
            "drawdown": Decimal("-25.5"),
            "sharpe": Decimal("2.7"),
        },
        {
            "k": 16,
            "return": Decimal("167.3"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("40.5"),
            "drawdown": Decimal("-24.9"),
            "sharpe": Decimal("2.5"),
        },
        {
            "k": 17,
            "return": Decimal("151.3"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("38.2"),
            "drawdown": Decimal("-24.2"),
            "sharpe": Decimal("1.5"),
        },
        {
            "k": 18,
            "return": Decimal("147.4"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("38.6"),
            "drawdown": Decimal("-23.8"),
            "sharpe": Decimal("1.3"),
        },
        {
            "k": 19,
            "return": Decimal("141.8"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("37.1"),
            "drawdown": Decimal("-23.8"),
            "sharpe": Decimal("1.0"),
        },
        {
            "k": 20,
            "return": Decimal("127.5"),
            "volatility": Decimal("16.8"),
            "turnover": Decimal("36.8"),
            "drawdown": Decimal("-24.5"),
            "sharpe": Decimal("0.1"),
        },
    ]

    assert result == expected_result
