from decimal import Decimal
from src import scenario2


def test_scenario2():
    result = scenario2.main()
    expected_result = [
        {
            "k": 3,
            "return": Decimal("37.1"),
            "volatility": Decimal("21.6"),
            "turnover": Decimal("52.0"),
            "drawdown": Decimal("-48.8"),
            "sharpe": Decimal("-4.1"),
        },
        {
            "k": 4,
            "return": Decimal("38.4"),
            "volatility": Decimal("21.2"),
            "turnover": Decimal("60.1"),
            "drawdown": Decimal("-45.2"),
            "sharpe": Decimal("-4.1"),
        },
        {
            "k": 5,
            "return": Decimal("38.9"),
            "volatility": Decimal("20.4"),
            "turnover": Decimal("66.6"),
            "drawdown": Decimal("-44.6"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 6,
            "return": Decimal("54.6"),
            "volatility": Decimal("20.3"),
            "turnover": Decimal("63.5"),
            "drawdown": Decimal("-42.6"),
            "sharpe": Decimal("-3.5"),
        },
        {
            "k": 7,
            "return": Decimal("66.9"),
            "volatility": Decimal("19.9"),
            "turnover": Decimal("66.9"),
            "drawdown": Decimal("-34.8"),
            "sharpe": Decimal("-2.9"),
        },
        {
            "k": 8,
            "return": Decimal("107.1"),
            "volatility": Decimal("19.3"),
            "turnover": Decimal("66.2"),
            "drawdown": Decimal("-28.7"),
            "sharpe": Decimal("-1.0"),
        },
        {
            "k": 9,
            "return": Decimal("97.5"),
            "volatility": Decimal("19.0"),
            "turnover": Decimal("64.9"),
            "drawdown": Decimal("-29.7"),
            "sharpe": Decimal("-1.5"),
        },
        {
            "k": 10,
            "return": Decimal("103.6"),
            "volatility": Decimal("18.7"),
            "turnover": Decimal("65.2"),
            "drawdown": Decimal("-30.2"),
            "sharpe": Decimal("-1.2"),
        },
        {
            "k": 11,
            "return": Decimal("129.3"),
            "volatility": Decimal("18.2"),
            "turnover": Decimal("65.1"),
            "drawdown": Decimal("-26.9"),
            "sharpe": Decimal("0.2"),
        },
        {
            "k": 12,
            "return": Decimal("150.8"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("55.3"),
            "drawdown": Decimal("-27.2"),
            "sharpe": Decimal("1.4"),
        },
        {
            "k": 13,
            "return": Decimal("110.3"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("51.5"),
            "drawdown": Decimal("-33.0"),
            "sharpe": Decimal("-0.9"),
        },
        {
            "k": 14,
            "return": Decimal("123.9"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("50.2"),
            "drawdown": Decimal("-30.9"),
            "sharpe": Decimal("-0.1"),
        },
        {
            "k": 15,
            "return": Decimal("144.8"),
            "volatility": Decimal("17.7"),
            "turnover": Decimal("48.0"),
            "drawdown": Decimal("-30.4"),
            "sharpe": Decimal("1.1"),
        },
        {
            "k": 16,
            "return": Decimal("141.3"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("48.2"),
            "drawdown": Decimal("-29.9"),
            "sharpe": Decimal("0.9"),
        },
        {
            "k": 17,
            "return": Decimal("121.4"),
            "volatility": Decimal("17.5"),
            "turnover": Decimal("46.2"),
            "drawdown": Decimal("-29.2"),
            "sharpe": Decimal("-0.2"),
        },
        {
            "k": 18,
            "return": Decimal("99.6"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("45.0"),
            "drawdown": Decimal("-29.2"),
            "sharpe": Decimal("-1.5"),
        },
        {
            "k": 19,
            "return": Decimal("94.1"),
            "volatility": Decimal("17.6"),
            "turnover": Decimal("44.5"),
            "drawdown": Decimal("-30.0"),
            "sharpe": Decimal("-1.8"),
        },
        {
            "k": 20,
            "return": Decimal("71.9"),
            "volatility": Decimal("17.7"),
            "turnover": Decimal("43.1"),
            "drawdown": Decimal("-32.0"),
            "sharpe": Decimal("-3.0"),
        },
    ]

    assert result == expected_result
