from decimal import Decimal
from src import scenario1


def test_scenario1():
    result = scenario1.main()
    expected_result = [
        {
            "k": 20,
            "result_type": "mean",
            "return": Decimal("52.4"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("105.1"),
            "drawdown": Decimal("-44.5"),
            "sharpe": Decimal("-3.3"),
        },
        {
            "k": 20,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 20,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 19,
            "result_type": "mean",
            "return": Decimal("44.0"),
            "volatility": Decimal("21.6"),
            "turnover": Decimal("105.7"),
            "drawdown": Decimal("-45.8"),
            "sharpe": Decimal("-3.8"),
        },
        {
            "k": 19,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 19,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 18,
            "result_type": "mean",
            "return": Decimal("43.7"),
            "volatility": Decimal("21.5"),
            "turnover": Decimal("106.5"),
            "drawdown": Decimal("-45.6"),
            "sharpe": Decimal("-3.8"),
        },
        {
            "k": 18,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 18,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 17,
            "result_type": "mean",
            "return": Decimal("54.0"),
            "volatility": Decimal("21.5"),
            "turnover": Decimal("108.2"),
            "drawdown": Decimal("-45.2"),
            "sharpe": Decimal("-3.3"),
        },
        {
            "k": 17,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 17,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 16,
            "result_type": "mean",
            "return": Decimal("41.1"),
            "volatility": Decimal("21.8"),
            "turnover": Decimal("108.3"),
            "drawdown": Decimal("-48.4"),
            "sharpe": Decimal("-3.9"),
        },
        {
            "k": 16,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 16,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 15,
            "result_type": "mean",
            "return": Decimal("50.3"),
            "volatility": Decimal("21.8"),
            "turnover": Decimal("108.6"),
            "drawdown": Decimal("-47.0"),
            "sharpe": Decimal("-3.4"),
        },
        {
            "k": 15,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 15,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 14,
            "result_type": "mean",
            "return": Decimal("54.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("108.8"),
            "drawdown": Decimal("-42.8"),
            "sharpe": Decimal("-3.3"),
        },
        {
            "k": 14,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 14,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 13,
            "result_type": "mean",
            "return": Decimal("48.8"),
            "volatility": Decimal("21.8"),
            "turnover": Decimal("109.5"),
            "drawdown": Decimal("-46.3"),
            "sharpe": Decimal("-3.5"),
        },
        {
            "k": 13,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 13,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 12,
            "result_type": "mean",
            "return": Decimal("39.6"),
            "volatility": Decimal("21.8"),
            "turnover": Decimal("109.5"),
            "drawdown": Decimal("-47.4"),
            "sharpe": Decimal("-3.9"),
        },
        {
            "k": 12,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 12,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 11,
            "result_type": "mean",
            "return": Decimal("33.8"),
            "volatility": Decimal("21.5"),
            "turnover": Decimal("108.4"),
            "drawdown": Decimal("-49.6"),
            "sharpe": Decimal("-4.3"),
        },
        {
            "k": 11,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 11,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 10,
            "result_type": "mean",
            "return": Decimal("38.6"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("107.6"),
            "drawdown": Decimal("-48.4"),
            "sharpe": Decimal("-4.0"),
        },
        {
            "k": 10,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 10,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 9,
            "result_type": "mean",
            "return": Decimal("55.8"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("107.0"),
            "drawdown": Decimal("-43.7"),
            "sharpe": Decimal("-3.2"),
        },
        {
            "k": 9,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 9,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 8,
            "result_type": "mean",
            "return": Decimal("37.4"),
            "volatility": Decimal("21.8"),
            "turnover": Decimal("103.7"),
            "drawdown": Decimal("-47.1"),
            "sharpe": Decimal("-4.1"),
        },
        {
            "k": 8,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 8,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 7,
            "result_type": "mean",
            "return": Decimal("47.6"),
            "volatility": Decimal("22.2"),
            "turnover": Decimal("101.5"),
            "drawdown": Decimal("-48.4"),
            "sharpe": Decimal("-3.5"),
        },
        {
            "k": 7,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 7,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 6,
            "result_type": "mean",
            "return": Decimal("62.4"),
            "volatility": Decimal("21.8"),
            "turnover": Decimal("97.4"),
            "drawdown": Decimal("-45.6"),
            "sharpe": Decimal("-2.9"),
        },
        {
            "k": 6,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 6,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 5,
            "result_type": "mean",
            "return": Decimal("54.9"),
            "volatility": Decimal("22.0"),
            "turnover": Decimal("91.8"),
            "drawdown": Decimal("-48.1"),
            "sharpe": Decimal("-3.2"),
        },
        {
            "k": 5,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 5,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 4,
            "result_type": "mean",
            "return": Decimal("59.7"),
            "volatility": Decimal("22.0"),
            "turnover": Decimal("87.0"),
            "drawdown": Decimal("-44.3"),
            "sharpe": Decimal("-3.0"),
        },
        {
            "k": 4,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 4,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
        {
            "k": 3,
            "result_type": "mean",
            "return": Decimal("58.4"),
            "volatility": Decimal("22.0"),
            "turnover": Decimal("77.0"),
            "drawdown": Decimal("-47.5"),
            "sharpe": Decimal("-3.1"),
        },
        {
            "k": 3,
            "result_type": "lowest",
            "return": Decimal("32.2"),
            "volatility": Decimal("22.4"),
            "turnover": Decimal("81.8"),
            "drawdown": Decimal("-53.1"),
            "sharpe": Decimal("-4.2"),
        },
        {
            "k": 3,
            "result_type": "highest",
            "return": Decimal("88.7"),
            "volatility": Decimal("21.7"),
            "turnover": Decimal("77.2"),
            "drawdown": Decimal("-49.7"),
            "sharpe": Decimal("-1.7"),
        },
    ]

    assert result == expected_result
